/*
 * can_parser.h
 *
 *  Created on: Jun 25, 2024
 *      Author: vital
 */

#ifndef INC_CAN_PARSER_H_
#define INC_CAN_PARSER_H_

#include "auto_control.h"
#include "string.h"

typedef uint8_t CanParser_StatusTypeDef;

#define CAN_PARSER_OK         				((CanParser_StatusTypeDef) 0U)

#define CAN_PARSER_ERROR     			 	((CanParser_StatusTypeDef) 1U)

#define CAN_PARSER_SPEED_LOW_BYTE			0U
#define CAN_PARSER_BRAKING_LOW_BYTE			2U
#define CAN_PARSER_STEERING_LOW_BYTE		4U
#define CAN_PARSER_GEAR_SHIFT_BYTE			6U
#define CAN_PARSER_MODE_SELECTION_BYTE		CAN_PARSER_GEAR_SHIFT_BYTE
#define CAN_PARSER_EBP_BYTE					7U
#define CAN_PARSER_FRONT_LIGHT_BYTE			CAN_PARSER_EBP_BYTE
#define CAN_PARSER_LEFT_LIGHT_BYTE			CAN_PARSER_EBP_BYTE
#define CAN_PARSER_RIGHT_LIGHT_BYTE			CAN_PARSER_EBP_BYTE
#define CAN_PARSER_SPEED_MODE_BYTE			CAN_PARSER_EBP_BYTE
#define CAN_PARSER_STATE_CONTROL_BYTE		CAN_PARSER_EBP_BYTE
#define CAN_PARSER_ADVANCED_MODE_BYTE		CAN_PARSER_EBP_BYTE
#define CAN_PARSER_SELF_DRIVING_BYTE		CAN_PARSER_EBP_BYTE

#define CAN_PARSER_GEAR_SHIFT_SHIFT			0U
#define CAN_PARSER_MODE_SELECTION_SHIFT		4U
#define CAN_PARSER_EBP_SHIFT				3U
#define CAN_PARSER_FRONT_LIGHT_SHIFT		4U
#define CAN_PARSER_LEFT_LIGHT_SHIFT			0U
#define CAN_PARSER_RIGHT_LIGHT_SHIFT		2U
#define CAN_PARSER_SPEED_MODE_SHIFT			6U
#define CAN_PARSER_STATE_CONTROL_SHIFT		1U
#define CAN_PARSER_ADVANCED_MODE_SHIFT		5U
#define CAN_PARSER_SELF_DRIVING_SHIFT		7U

#define CAN_PARSER_GEAR_SHIFT_MASK			0b00001111
#define CAN_PARSER_MODE_SELECTION_MASK		0b00001111
#define CAN_PARSER_EBP_MASK					0b00000001
#define CAN_PARSER_FRONT_LIGHT_MASK			0b00000001
#define CAN_PARSER_LEFT_LIGHT_MASK			0b00000001
#define CAN_PARSER_RIGHT_LIGHT_MASK			0b00000001
#define CAN_PARSER_SPEED_MODE_MASK			0b00000001
#define CAN_PARSER_STATE_CONTROL_MASK		0b00000001
#define CAN_PARSER_ADVANCED_MODE_MASK		0b00000001
#define CAN_PARSER_SELF_DRIVING_MASK		0b00000001


CanParser_StatusTypeDef can_parser_from_auto_control_to_array(auto_control_data_t auto_control_data,uint8_t* data);



#endif /* INC_CAN_PARSER_H_ */
